README.md
CRD refers to Custom Resource Definition, not Customer.
=> Change customer to custom

docs/pulsar_connection.md, docs/pulsar_namespace.md, docs/pulsar_permission.md, docs/pulsar_tenant.md, docs/pulsar_topic.md
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> [docs] Fix API version group

docs/pulsar_connection.md, docs/pulsar_namespace.md, docs/pulsar_permission.md, docs/pulsar_tenant.md, docs/pulsar_topic.md
Fix doc issue.
Update crd name.
=> [docs] Use crd full name in kubectl command

go.mod, go.sum
Fixes #70 
Failed to create a non-partitioned topic. Because in the current version of pulsarctl, it didn't support to create a non-partitioned topic.
Upgrade pulsarctl version to v0.4.3-0.20220914035517-f17661719284.
*(or)*
*(or)*
*(example:)*
(If this PR contains doc …
=> Upgrade pulsarctl to v0.4.3-0.20220914035517-f17661719284

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> Bump appVersion to v0.2.0

charts/pulsar-resources-operator/templates/deployment.yaml, charts/pulsar-resources-operator/values.yaml
Signed-off-by: ericsyh <ericshenyuhao@outlook.com>
Fixes #75 
Update the image config in the values:
1. Make the `kube-rbac-proxy` container configurable via values.yaml
2. Add the key for resource controller container in values.yaml 
*(or)*
*(or)*
*(example:)*
- *Added integration tests for …
=> fix: make the hard coded container with template

.github/workflows/chart-test.yml, .github/workflows/e2e_test.yml, .github/workflows/release-operator.yml, .github/workflows/style.yml, charts/pulsar-resources-operator/Chart.yaml, lintconf.yaml
Fixes #86 
Improve the chart test.
- Add `helm template` to render the chart with multiple k8s versions.
- Use `yamllint` to lint the rendered manifests.
- Add `ct install` to install the chart.
*(or)*
*(or)*
*(example:)* …
=> [CI] Improve chart test

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarconnections.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsargeoreplications.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarpermissions.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsartenants.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsartopics.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> ci: bump chart to v0.3.0

charts/pulsar-resources-operator/templates/role.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix: role permission

docs/pulsar_connection.md, docs/pulsar_geo_replication.md
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix: update docs

docs/pulsar_connection.md, docs/pulsar_geo_replication.md
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix: update geo cr examples. 

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarconnections.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml, ct.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> ci: bump chart version to v0.3.1

api/v1alpha1/pulsarconnection_types.go, config/crd/bases/resource.streamnative.io_pulsarconnections.yaml
Fixes #99 
Optimize the output fields of the pulsarconnection when using `kubectl get pulsarconnection` or `kubectl get pulsarconnection -owide`.
- The default columns will be `NAME`,`ADMIN_SERVICE_URL`,`BROKER_SERVICE_URL`, and `READY`.
- Add `ADMIN_SERVICE_SECURE_URL`, `BROKER_SERVICE_SECURE_URL`,` GENERATION`, and `OBSERVED_GENERATION` into the wide output.
=> feat: optimize the output fields of the pulsarconnection

README.md
Fixes #<xyz>
Dpdate readme about upgrading chart.
Note that when doing the upgrade, the customers need to apply the crds manually. Because the helm doesn't support it.
*(or)*
*(or)*
*(example:)* …
=> docs: update readme about upgrading chart

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> ci: bump chart version to 0.3.2

charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarconnections.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix: add crd changes to the chart

.github/workflows/e2e_test.yml, charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml, charts/pulsar-resources-operator/values.schema.json, charts/pulsar-resources-operator/values.yaml, config/default/manager_auth_proxy_patch.yaml
Fixes #106 
*(or)*
*(or)*
*(example:)*
(If this PR …
=> chore: upgrade kube-rbac-proxy to v0.14.1

CONTRIBUTING.md, README.md
Add contributing guide.
Add contributing guide.
*(or)*
*(or)*
*(example:)*
=> doc: add contributing guide

.github/workflows/chart-test.yml
Fixes #110 
Check if the crds are up to date before releasing the chart.
Add ci step to check the crd files under the directory `config` and `chart`.
Adding a new line `# New line to test crd check` in `config/crd/bases/resource.streamnative.io_pulsarconnections.yaml`, and commit it to trigger the ci test.
The result meets the expectation, the action `chart-test` went failure.
You can find the result in this action.
https://github.com/streamnative/pulsar-resources-operator/actions/runs/4950190374/jobs/8853461736
*(or)*
*(or)* …
=> ci: add step to check if the crds are up to date

docs/pulsar_namespace.md, docs/pulsar_topic.md
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> update doc for time units

.github/workflows/e2e_test.yml, .github/workflows/release-operator.yml, .github/workflows/style.yml, Dockerfile, api/v1alpha1/groupversion_info.go, go.mod, go.sum
Fixes #115 
Fix CVE-2023-24538 and CVE-2023-24540
Upgrade go to 1.19.9
*(or)*
*(or)*
*(example:)*
=> chore: upgrade go to 1.19

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml
Bump chart version to v0.3.4
*(or)*
*(or)*
*(example:)*
=> ci: bump chart version to v0.3.4

Makefile, charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarnamespaces.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsartopics.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml
Fixes #<xyz>
Bump chart to v0.4.0
*(or)*
*(or)*
*(example:)*
(If you need help on updating docs, create a doc …
=> chore: bump chart to v0.4.0

charts/pulsar-resources-operator/Chart.yaml
Fixes #120 
*(or)*
*(or)*
*(example:)*
Check …
=> bump kubeVersion in chart configuration.

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> chore: bump chart to v0.4.1

pkg/admin/impl.go
…(#132)
Cherry-pick the fix pr #132 to branch-0.4.0
*(or)*
*(or)*
*(example:)*
=> cherry pick #132

docs/pulsar_connection.md
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix auth format in doc

Dockerfile, Makefile, controllers/pulsarconnection_controller.go, pkg/connection/reconcile_geo_replication.go, pkg/connection/reconciler.go
Fixes #137 
Block the deletion of the destination pulsar connection when there is still a PulsarGeoReplication referenced it.
*(or)*
*(or)*
*(example:)*
(Please …
=> fix: block the deletion of the destination pulsar connection 

charts/pulsar-resources-operator/values.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> update image registry in chart

.github/workflows/release-operator.yml, Makefile, config/manifests-redhat/bases/pulsar-resources-operator.clusterserviceversion.yaml, redhat.Dockerfile
Master Issue: #58 
*(or)*
*(or)*
*(example:)*
=> ci: support redhat certification

.github/operatorhub/community-operators, .licenserc.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> ci: add pr template

Makefile
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> chore: update rbac container in the makefile

api/v1alpha1/common.go, go.mod, go.sum, pkg/admin/interface.go, pkg/connection/reconciler.go, tests/go.mod, tests/go.sum
Fixes #150 
*(or)*
*(or)*
*(example:)*
Check …
=> feat: support oauth2 scope field

api/v1alpha1/common.go
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix: make oauth2 scope field optional

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarconnections.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarpermissions.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsartenants.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml, config/crd/bases/resource.streamnative.io_pulsarconnections.yaml, config/crd/bases/resource.streamnative.io_pulsarpermissions.yaml, config/crd/bases/resource.streamnative.io_pulsartenants.yaml, config/rbac/role.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> chore: bump chart to the 0.4.3 release

pkg/connection/reconcile_geo_replication.go, pkg/connection/reconciler.go
When remote pulsar connection changes, we should sync the change to local pulsar cluster.
=> Fix geo sync of remote connection

.github/workflows/chart-test.yml, ct.yaml
Fixes #133 
Improve the chart test, to install the chart on multiple k8s versions.
Add more sub jobs to run the chart installation.
*(or)*
*(or)*
*(example:)*
=> ci: install chart on k8s v1.20

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarconnections.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsargeoreplications.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarnamespaces.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarpermissions.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsartenants.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsartopics.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml, config/crd/bases/resource.streamnative.io_pulsarconnections.yaml, config/crd/bases/resource.streamnative.io_pulsargeoreplications.yaml, config/crd/bases/resource.streamnative.io_pulsarnamespaces.yaml, config/crd/bases/resource.streamnative.io_pulsarpermissions.yaml, config/crd/bases/resource.streamnative.io_pulsartenants.yaml, config/crd/bases/resource.streamnative.io_pulsartopics.yaml, config/rbac/role.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> chore: upgrade chart to 0.4.5

.github/CODEOWNERS, .github/openshift/community-operators-prod, .github/workflows/release-certificated-olm.yaml, .github/workflows/release-community-olm.yaml, .licenserc.yaml, config/scorecard/patches/basic.config.yaml, config/scorecard/patches/olm.config.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> ci: add support for olm certifacte release

Makefile
Fixes #<xyz>
Update the olm support version in the annotation. 
Update the olm support version in the annotation. 
*(or)*
*(or)*
*(example:)*
(If you …
=> build: update the olm release annotation

pkg/admin/impl.go, tests/operator/resources_test.go
Fixes https://github.com/streamnative/eng-support-tickets/issues/954
=> Fix partitioned topic not change

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> chore: upgrade the chart to 0.4.7

docs/pulsar_topic.md
Fixes #<xyz>
From the https://github.com/streamnative/pulsar-resources-operator/pull/185, we supported updating topic partitions in the `PulsarTopic` object. 
*(or)*
*(or)*
*(example:)*
- *Extended integration test for …
=> fix: update the PulsarTopic doc to remove the partition limitation. 

docs/pulsar_connection.md
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix client id mismatch

Makefile, controllers/pulsarconnection_controller.go, pkg/connection/reconcile_geo_replication.go, pkg/connection/reconcile_namespace.go, pkg/connection/reconcile_permission.go, pkg/connection/reconcile_tenant.go, pkg/connection/reconcile_topic.go, pkg/connection/reconciler.go
Fixes https://github.com/streamnative/eng-support-tickets/issues/1019
=> improve log output

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml, charts/pulsar-resources-operator/values.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> chore: bump chart to 0.4.8

Dockerfile, go.mod, go.sum
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> chore: upgrade pulsar client lib and dockerfile

Dockerfile, redhat.Dockerfile
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> update the dockerfile

.github/workflows/release-operator.yml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix openshift-preflight

redhat.Dockerfile
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> change to use the ubi-minimal

.github/workflows/chart-test.yml, .github/workflows/release-operator.yml, charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml, charts/pulsar-resources-operator/values.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> update resource operator chart

.gitignore, config/manifests-redhat/bases/pulsar-resources-operator.clusterserviceversion.yaml, config/manifests/bases/pulsar-resources-operator.clusterserviceversion.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix: add olm required labels

docs/pulsar_connection.md
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> doc: update the pulsarconnection doc and examples

.github/workflows/release-operator.yml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> feat: support release image to DockerHub

Dockerfile
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> Upgrade all Alpine packages at build time

.github/workflows/e2e_test.yml, .github/workflows/release-operator.yml, .github/workflows/style.yml, go.mod, go.sum
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> chore: upgrade workflow to go 1.21

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/README.md, charts/pulsar-resources-operator/tests/deployment_test.yaml, charts/pulsar-resources-operator/values.schema.json, charts/pulsar-resources-operator/values.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> chore: upgrade chart and change the image registry

pkg/connection/reconciler.go
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix: fix the reconcile order for packages and functions / connectors

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> release helm charts 0.5.0 with non-rc app version

.github/workflows/release-community-olm.yaml, .github/workflows/release-operator.yml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix: olm release CI bug

pkg/admin/dummy.go, pkg/admin/impl.go, pkg/admin/interface.go, pkg/connection/reconcile_function.go, pkg/connection/reconcile_package.go, pkg/connection/reconcile_sink.go, pkg/connection/reconcile_source.go, tests/operator/resources_test.go
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix function reconcile uses incorrect status to check if update or not

charts/pulsar-resources-operator/README.md, charts/pulsar-resources-operator/templates/deployment.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml, charts/pulsar-resources-operator/values.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> remove the kube-rbac-proxy

.github/workflows/release-operator.yml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix the release ci

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarconnections.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarfunctions.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsargeoreplications.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarnamespaces.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarpackages.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarpermissions.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarsinks.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarsources.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsartenants.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsartopics.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml, config/crd/bases/resource.streamnative.io_pulsarconnections.yaml, config/crd/bases/resource.streamnative.io_pulsarfunctions.yaml, config/crd/bases/resource.streamnative.io_pulsargeoreplications.yaml, config/crd/bases/resource.streamnative.io_pulsarnamespaces.yaml, config/crd/bases/resource.streamnative.io_pulsarpackages.yaml, config/crd/bases/resource.streamnative.io_pulsarpermissions.yaml, config/crd/bases/resource.streamnative.io_pulsarsinks.yaml, config/crd/bases/resource.streamnative.io_pulsarsources.yaml, config/crd/bases/resource.streamnative.io_pulsartenants.yaml, config/crd/bases/resource.streamnative.io_pulsartopics.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> chore: bump chart to 0.5.4

Dockerfile, go.mod, redhat.Dockerfile, tests/go.mod
fixes https://github.com/streamnative/eng-support-tickets/issues/1501
=> Upgrade go version to fix CVE-2024-24789, CVE-2024-24790

.golangci.yml, controllers/pulsarconnection_controller.go, pkg/connection/reconciler.go
Fixes #<xyz>
When using OAuth2 with Key SecretRef, the secret hash will not update to status and may causing the missing refresh when secret changed.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for …
=> fix oauth2 key secret ref hash

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> chore: bump chart to v0.5.6

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarnamespaces.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> bump chart to 0.5.7

main.go
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> feat: add retry count var

pkg/connection/reconcile_function.go, pkg/connection/reconcile_geo_replication.go, pkg/connection/reconcile_package.go, pkg/connection/reconcile_permission.go, pkg/connection/reconcile_sink.go, pkg/connection/reconcile_source.go, pkg/connection/reconcile_tenant.go
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> optimize the controller reconcile

Makefile
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> update openshift support version

.github/workflows/release-operator.yml
Fixes #264 
*(or)*
*(or)*
*(example:)*
Check …
=> Upgrade openshift-preflight to `1.10.2`

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarnamespaces.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsartopics.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> bump chart to 0.6.2

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml
The 0.6.3 missed some CRD changes
=> bump chart to 0.6.4

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/templates/role.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> Bump chart to 0.6.5

.github/workflows/release-operator.yml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> bump redhat preflight to 1.11.1

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/README.md, charts/pulsar-resources-operator/tests/deployment_test.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> bump chart to `v0.8.0-rc.2`

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/README.md, charts/pulsar-resources-operator/tests/deployment_test.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> release helm charts v0.8.0

charts/pulsar-resources-operator/templates/role.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix helm chart role for sn cloud resources

.github/workflows/release-operator.yml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix bundle release action

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/README.md, charts/pulsar-resources-operator/crds/resource.streamnative.io_computeflinkdeployments.yaml, charts/pulsar-resources-operator/tests/deployment_test.yaml, config/crd/bases/resource.streamnative.io_computeflinkdeployments.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> bump helm charts to v0.8.1

.github/workflows/chart-test.yml, Makefile, charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/README.md, charts/pulsar-resources-operator/crds/resource.streamnative.io_computeflinkdeployments.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_computeworkspaces.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarfunctions.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsargeoreplications.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarnamespaces.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarnsisolationpolicies.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarpackages.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarpermissions.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarsinks.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsarsources.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsartenants.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_pulsartopics.yaml, charts/pulsar-resources-operator/crds/resource.streamnative.io_secrets.yaml, charts/pulsar-resources-operator/templates/role.yaml, scripts/sync_rules.py
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> bump helm charts 0.9.0

charts/pulsar-resources-operator/Chart.yaml, charts/pulsar-resources-operator/README.md
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> release v0.9.1 helm chart

charts/pulsar-resources-operator/Chart.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> chore: bump the operator to 0.9.2

.github/workflows/e2e_test.yml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix dockerhub login in ci

.github/workflows/release-operator.yml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> bump preflight 1.14.0

api/v1alpha1/pulsarfunction_types.go, api/v1alpha1/zz_generated.deepcopy.go, docs/pulsar_sink.md, pkg/admin/impl.go, tests/utils/spec.go
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix: Use pointer types for boolean fields in PulsarFunction to prevent omitempty issues

config/samples/resource_v1alpha1_streamnativecloudconnection.yaml, docs/streamnative_cloud_connection.md
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> docs(samples): remove k8s Secret from alm-examples and use stringData in docs
